config/routes.rb
Rails.application.routes.draw do

root 'board#index'
post '/move' => 'board#move'
post '/start' => 'board#start'
post '/create' => 'board#create_room'
post '/update' => 'board#update_gamedata'
post '/load' => 'board#load_game'
post '/sendchat' => 'chat#send_chat'
get '/game' => 'board#game'
post '/game' => 'board#game'

end

app/models/base.rb
class Base
  def write
    Redis.current.set(room, to_json) unless room.blank?
  end

  def read
    JSON.parse(Redis.current.get(room))
  rescue
    {}
  end

  def read!
    data = read
    self.room = data['room']
    self.guestname = data['guestname']
    self.hostname = data['hostname']
    self.board = data['board']
    self.score = data['score']
    self.turn = data['turn']
    self.gameover = data['gameover']
  end

  def self.exists?(key)
    Redis.current.exists(key)
  end
end

app/models/room.rb
class Room < Base

  attr_accessor :room, :hostname, :guestname, :board, :turn, :score, :gameover

  def initialize(attributes = {})
    game_initializer unless Room.exists?(attributes[:room])
    @hostin = 0
    @guestin = 0
    @turn = attributes[:hostname]
    @room = attributes[:room]
    @hostname = attributes[:hostname]
    @guestname = attributes[:guestname]
  end

  def player_can_join?(params)
    if room == params[:room]
      return true if hostname == params[:name] || guestname == params[:name]
    end
    false
  end

  private

  def game_initializer
    game = GameEngine.new
    @board = game.board
    @score = game.score
    @gameover = game.gameover
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/board_controller.rb
class BoardController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_filter :set_room, only: [:create_room, :load_game, :move, :game, :send_chat]
  respond_to :html, :js

  include Movable

  def index
  end

  def game
    @room.read!
    if @room.player_can_join?(room_params)
      session[:room] = room_params[:room]
      session[:user] = room_params[:name]
    else
      redirect_to root_path, alert: 'Sorry! We couldn\'t
                                 get you into the room!'
    end
  end

  def create_room
    if !Room.exists?(room_params[:room]) && @room.write
      redirect_to root_path, notice: 'Room successfully created!
                             Feel free to join the room whenever you want.'
    else
      redirect_to root_path, alert: 'Sorry! We couldn\'t create
                             the room for you!'
    end
  end

  def load_game
    gamedata = @room.read
    render json: gamedata
  end

  def move
    @room.read!
    return unless @room.turn == room_params['user']
    make_move(@room, room_params['move'])
    @room.write
    FayeSender.broadcast("/#{room_params['room']}", @room.read)
    render json: @room.read
  end

  private

  def set_room
    @room = Room.new(room_params)
  end

  def room_params
    params.require(:room).permit(:room, :hostname, :guestname, :name, :user, :move)
  end
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def send_chat
    FayeSender.message("/#{chat_params['room']}", chat_params[:user], chat_params[:message])
    render nothing: true
  end

  private

  def chat_params
    params.require(:chat).permit(:room, :user, :message)
  end

end

app/controllers/concerns/movable.rb
module Movable
  extend ActiveSupport::Concern

  def toggle_turn(data)
    if data.turn == data.hostname
      data.turn = data.guestname
    else
      data.turn = data.hostname
    end
  end

  def make_move(gamedata, move)
    game = GameEngine.new
    game.main_setter(gamedata.board, gamedata.score, gamedata.gameover)
    game.move(move)

    gamedata.board = game.board
    gamedata.score = game.score
    gamedata.gameover = game.gameover
    toggle_turn(gamedata)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_in(room, user)

  end

  def user_out(room, user)
    
  end
end

app/helpers/board_helper.rb
module BoardHelper

end

app/views/board/game.html.erb
<body onload="loadgame()">
	<div class="row" style="margin-top: 2em" data-equalizer>
		<div class="game">
			<div class="large-12 small-centered columns">
				<div class="panel">
					<div><span>Room: </span><h4 id="room-name"><%= session[:room] %></h4></div>
					<div><span>Your name: </span><h4 id="user-name"><%= session[:user] %></h4></div>
					<div><span>Who's turn is it now: <span><span id="turn"></span></div>
					<div><span>Current Score:</span><span id="score">0</span></div>
				</div>
			</div>

			<div class="large-6 columns" data-equalizer-watch>
				<div class="game-container">
					<div class="game-message">
						<p></p>
						<div class="lower">
							<a class="keep-playing-button">Keep going</a>
							<a class="retry-button">Try again</a>
							<a class="save-button">Save your score</a>

						</div>

					</div>
					<div class="grid-container">
						<div class="grid-row">
							<div class="grid-cell"></div>
							<div class="grid-cell"></div>
							<div class="grid-cell"></div>
							<div class="grid-cell"></div>
						</div>
						<div class="grid-row">
							<div class="grid-cell"></div>
							<div class="grid-cell"></div>
							<div class="grid-cell"></div>
							<div class="grid-cell"></div>
						</div>
						<div class="grid-row">
							<div class="grid-cell"></div>
							<div class="grid-cell"></div>
							<div class="grid-cell"></div>
							<div class="grid-cell"></div>
						</div>
						<div class="grid-row">
							<div class="grid-cell"></div>
							<div class="grid-cell"></div>
							<div class="grid-cell"></div>
							<div class="grid-cell"></div>
						</div>
					</div>

					<div class="tile-container" id="tile-container">

					</div>
				</div>

			</div>
			<div class="large-6 columns" style="margin-top: 16px" data-equalizer-watch>
				<div class="scores-container"></div>

					<textarea type="text" readonly="readonly" rows="25" id="chat-area"></textarea>
					<%= form_tag(sendchat_path,  method: "post", remote: true) do %>
					<div class="row collapse">
						<input name="chat[user]" type="hidden" value="<%= session[:user] %>" />
						<input name="chat[room]" type="hidden" value="<%= session[:room] %>" />
						<div class="small-10 columns">
							<input type="text" placeholder="Type your message here.." id="chat-input", name="chat[message]" >
						</div>
						<div class="small-2 columns">
							<%= submit_tag("Send", class: "button postfix") %>
						</div>
					</div>
					<% end %>
			</div>
		</div>
	</div>
</body>

app/views/board/game.js.erb
$(document).ready(function() {
alert("salam yare");
<% binding.pry %>
)};

app/views/board/index.html.erb
<div class="row" style="margin-top: 8em" data-equalizer>
	<div class="large-12 columns">
		<%= render partial: 'layouts/messages' %>
	</div>

	<div class="large-6 columns">
		<div class="panel" data-equalizer-watch>
			<h4>Create a new room</h4>
			<%= form_tag(create_path,  method: "post") do %>
			<input type="text" placeholder="Room Name" name="room[room]"/>
			<label for="hostname">Your name:</label>
			<input type="text" id="hostname"  name="room[hostname]"/>
			<label for="gurstname">Guest name:</label>
			<input type="text" id="guestname"  name="room[guestname]"/>
			<%= submit_tag("CREATE", class: "button tiny") %>
			<% end %>
		</div>

	</div>

	<div class="large-6 columns">
			<div class="panel" data-equalizer-watch>
				<h4>Join a room</h4>
			<%= form_tag(game_path,  method: "post") do %>
			<input type="text" placeholder="Room Name" name="room[room]"/>
			<label for="hostname">Your name:</label>
			<input type="text" id="hostname"  name="room[name]"/>
			<%= submit_tag("JOIN", class: "button tiny") %>
			<% end %>
		</div>
	</div>

	<div class="large-12 columns">
		<div class="panel">
			<h4>This version of the game</h4>
			<p>
				This is a 2 player version of 2048. Players take turn to play.</br>
			</p>
		</div>
	</div>
</div>

<!-- temp workaround! foundation's bug does not let it be included in application.js -->
<script>
	$(document).foundation();
</script>

app/views/layouts/_messages.html.erb
<%if notice.present?%>
<div data-alert class="alert-box info">
	  <%= notice %>
  <a href="#" class="close">&times;</a>
</div>
<% elsif alert.present? %>
<div data-alert class="alert-box warning">
	 <%= alert %>
  <a href="#" class="close">&times;</a>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>
  <link href='http://fonts.googleapis.com/css?family=Roboto:300,400,400italic,500,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400italic,400,600,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application", 'http://localhost:9292/faye.js'%>
  <%= csrf_meta_tags %>
</head>

<body>
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><a href="#">2player2048</a></h1>
      </li>
      <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>
</nav>
<%= yield %>

</body>
</html>